package com.trips.entity;
// Generated May 1, 2017 9:59:44 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "car", catalog = "project_2")
public class Car implements java.io.Serializable {

	private Integer carId;
	private Driver driver;
	private String carType;
	private Integer numSeatType1;
	private Integer numSeatType2;
	private String licensePlate;
	private Set<WeekSchedule> weekSchedules = new HashSet<WeekSchedule>(0);
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<ScheduleControl> scheduleControls = new HashSet<ScheduleControl>(0);

	public Car() {
	}

	public Car(Driver driver, String licensePlate) {
		this.driver = driver;
		this.licensePlate = licensePlate;
	}

	public Car(Driver driver, String carType, Integer numSeatType1, Integer numSeatType2, String licensePlate,
			Set<WeekSchedule> weekSchedules, Set<Bill> bills, Set<ScheduleControl> scheduleControls) {
		this.driver = driver;
		this.carType = carType;
		this.numSeatType1 = numSeatType1;
		this.numSeatType2 = numSeatType2;
		this.licensePlate = licensePlate;
		this.weekSchedules = weekSchedules;
		this.bills = bills;
		this.scheduleControls = scheduleControls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "car_id", unique = true, nullable = false)
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "driver_id", nullable = false)
	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	@Column(name = "car_type", length = 45)
	public String getCarType() {
		return this.carType;
	}

	public void setCarType(String carType) {
		this.carType = carType;
	}

	@Column(name = "num_seat_type_1")
	public Integer getNumSeatType1() {
		return this.numSeatType1;
	}

	public void setNumSeatType1(Integer numSeatType1) {
		this.numSeatType1 = numSeatType1;
	}

	@Column(name = "num_seat_type_2")
	public Integer getNumSeatType2() {
		return this.numSeatType2;
	}

	public void setNumSeatType2(Integer numSeatType2) {
		this.numSeatType2 = numSeatType2;
	}

	@Column(name = "license_plate", nullable = false, length = 45)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<WeekSchedule> getWeekSchedules() {
		return this.weekSchedules;
	}

	public void setWeekSchedules(Set<WeekSchedule> weekSchedules) {
		this.weekSchedules = weekSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<ScheduleControl> getScheduleControls() {
		return this.scheduleControls;
	}

	public void setScheduleControls(Set<ScheduleControl> scheduleControls) {
		this.scheduleControls = scheduleControls;
	}

}
