package com.trips.entity;
// Generated Apr 25, 2017 3:44:44 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "project_2")
public class Station implements java.io.Serializable {

	private Integer stationId;
	private String stationName;
	private Set<Bill> bills = new HashSet<Bill>(0);
	private Set<Bill> bills_1 = new HashSet<Bill>(0);

	public Station() {
	}

	public Station(String stationName) {
		this.stationName = stationName;
	}

	public Station(String stationName, Set<Bill> bills, Set<Bill> bills_1) {
		this.stationName = stationName;
		this.bills = bills;
		this.bills_1 = bills_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "station_id", unique = true, nullable = false)
	public Integer getStationId() {
		return this.stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	@Column(name = "station_name", nullable = false, length = 45)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "station")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "station")
	public Set<Bill> getBills_1() {
		return this.bills_1;
	}

	public void setBills_1(Set<Bill> bills_1) {
		this.bills_1 = bills_1;
	}

}
