package com.trips.entity;
// Generated May 1, 2017 9:59:44 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "project_2")
public class Station implements java.io.Serializable {

	private Integer stationId;
	private Route route;
	private String stationName;
	private Byte order;
	private Set<Bill> billsForStationIdLast = new HashSet<Bill>(0);
	private Set<Bill> billsForStationIdFirst = new HashSet<Bill>(0);

	public Station() {
	}

	public Station(String stationName) {
		this.stationName = stationName;
	}

	public Station(Route route, String stationName, Byte order, Set<Bill> billsForStationIdLast,
			Set<Bill> billsForStationIdFirst) {
		this.route = route;
		this.stationName = stationName;
		this.order = order;
		this.billsForStationIdLast = billsForStationIdLast;
		this.billsForStationIdFirst = billsForStationIdFirst;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "station_id", unique = true, nullable = false)
	public Integer getStationId() {
		return this.stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "route_id")
	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	@Column(name = "station_name", nullable = false, length = 45)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@Column(name = "order")
	public Byte getOrder() {
		return this.order;
	}

	public void setOrder(Byte order) {
		this.order = order;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByStationIdLast")
	public Set<Bill> getBillsForStationIdLast() {
		return this.billsForStationIdLast;
	}

	public void setBillsForStationIdLast(Set<Bill> billsForStationIdLast) {
		this.billsForStationIdLast = billsForStationIdLast;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByStationIdFirst")
	public Set<Bill> getBillsForStationIdFirst() {
		return this.billsForStationIdFirst;
	}

	public void setBillsForStationIdFirst(Set<Bill> billsForStationIdFirst) {
		this.billsForStationIdFirst = billsForStationIdFirst;
	}

}
