package com.trips.entity;
// Generated Apr 29, 2017 1:59:17 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "project_2")
public class Station implements java.io.Serializable {

	private Integer stationId;
	private String stationName;
	private Set<Bill> billsForStationIdLast = new HashSet<Bill>(0);
	private Set<Route> routesForOriginStationId = new HashSet<Route>(0);
	private Set<Route> routesForOriginStationId_1 = new HashSet<Route>(0);
	private Set<Route> routesForDestinationStationId = new HashSet<Route>(0);
	private Set<Bill> billsForStationIdLast_1 = new HashSet<Bill>(0);
	private Set<Bill> billsForStationIdFirst = new HashSet<Bill>(0);
	private Set<Route> routesForDestinationStationId_1 = new HashSet<Route>(0);
	private Set<Bill> billsForStationIdFirst_1 = new HashSet<Bill>(0);

	public Station() {
	}

	public Station(String stationName) {
		this.stationName = stationName;
	}

	public Station(String stationName, Set<Bill> billsForStationIdLast, Set<Route> routesForOriginStationId,
			Set<Route> routesForOriginStationId_1, Set<Route> routesForDestinationStationId,
			Set<Bill> billsForStationIdLast_1, Set<Bill> billsForStationIdFirst,
			Set<Route> routesForDestinationStationId_1, Set<Bill> billsForStationIdFirst_1) {
		this.stationName = stationName;
		this.billsForStationIdLast = billsForStationIdLast;
		this.routesForOriginStationId = routesForOriginStationId;
		this.routesForOriginStationId_1 = routesForOriginStationId_1;
		this.routesForDestinationStationId = routesForDestinationStationId;
		this.billsForStationIdLast_1 = billsForStationIdLast_1;
		this.billsForStationIdFirst = billsForStationIdFirst;
		this.routesForDestinationStationId_1 = routesForDestinationStationId_1;
		this.billsForStationIdFirst_1 = billsForStationIdFirst_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "station_id", unique = true, nullable = false)
	public Integer getStationId() {
		return this.stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	@Column(name = "station_name", nullable = false, length = 45)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByStationIdLast")
	public Set<Bill> getBillsForStationIdLast() {
		return this.billsForStationIdLast;
	}

	public void setBillsForStationIdLast(Set<Bill> billsForStationIdLast) {
		this.billsForStationIdLast = billsForStationIdLast;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByOriginStationId")
	public Set<Route> getRoutesForOriginStationId() {
		return this.routesForOriginStationId;
	}

	public void setRoutesForOriginStationId(Set<Route> routesForOriginStationId) {
		this.routesForOriginStationId = routesForOriginStationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByOriginStationId")
	public Set<Route> getRoutesForOriginStationId_1() {
		return this.routesForOriginStationId_1;
	}

	public void setRoutesForOriginStationId_1(Set<Route> routesForOriginStationId_1) {
		this.routesForOriginStationId_1 = routesForOriginStationId_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByDestinationStationId")
	public Set<Route> getRoutesForDestinationStationId() {
		return this.routesForDestinationStationId;
	}

	public void setRoutesForDestinationStationId(Set<Route> routesForDestinationStationId) {
		this.routesForDestinationStationId = routesForDestinationStationId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByStationIdLast")
	public Set<Bill> getBillsForStationIdLast_1() {
		return this.billsForStationIdLast_1;
	}

	public void setBillsForStationIdLast_1(Set<Bill> billsForStationIdLast_1) {
		this.billsForStationIdLast_1 = billsForStationIdLast_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByStationIdFirst")
	public Set<Bill> getBillsForStationIdFirst() {
		return this.billsForStationIdFirst;
	}

	public void setBillsForStationIdFirst(Set<Bill> billsForStationIdFirst) {
		this.billsForStationIdFirst = billsForStationIdFirst;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByDestinationStationId")
	public Set<Route> getRoutesForDestinationStationId_1() {
		return this.routesForDestinationStationId_1;
	}

	public void setRoutesForDestinationStationId_1(Set<Route> routesForDestinationStationId_1) {
		this.routesForDestinationStationId_1 = routesForDestinationStationId_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stationByStationIdFirst")
	public Set<Bill> getBillsForStationIdFirst_1() {
		return this.billsForStationIdFirst_1;
	}

	public void setBillsForStationIdFirst_1(Set<Bill> billsForStationIdFirst_1) {
		this.billsForStationIdFirst_1 = billsForStationIdFirst_1;
	}

}
