package com.trips.entity;
// Generated Apr 29, 2017 2:20:02 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WeekSchedule generated by hbm2java
 */
@Entity
@Table(name = "week_schedule", catalog = "project_2")
public class WeekSchedule implements java.io.Serializable {

	private int weekday;
	private Car car;
	private Route route;
	private Date dateTime;

	public WeekSchedule() {
	}

	public WeekSchedule(int weekday, Car car, Route route, Date dateTime) {
		this.weekday = weekday;
		this.car = car;
		this.route = route;
		this.dateTime = dateTime;
	}

	@Id

	@Column(name = "weekday", unique = true, nullable = false)
	public int getWeekday() {
		return this.weekday;
	}

	public void setWeekday(int weekday) {
		this.weekday = weekday;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "car_id", nullable = false)
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "route_id", nullable = false)
	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
